{% set name = "translators" %}
{% set version = "5.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/translators-{{ version }}.tar.gz
  sha256: 97d49525dc94b6d48637f67188c21880f59f2925c498fa12b408728032b27fd0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests >=2.28.1
    - pyexecjs >=1.5.1
    - lxml >=4.9.1
    - pathos >=0.2.9
    - cryptography >=38.0.1

test:
  imports:
    - translators
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uliontse/translators
  summary: Translators is a library which aims to bring free, multiple, enjoyable translation to individuals and students in Python.
  dev_url: https://github.com/UlionTse/translators
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - UlionTse
