{% set name = "translators" %}
{% set version = "5.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/translators-{{ version }}.tar.gz
  sha256: 9d7944645c74e6828aae726237ae7203132e8b1d1727478e9d650214db8c6a27

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - httpx >=0.28.1
    - requests >=2.32.3
    - niquests >=3.8.0
    - pyexecjs >=1.5.1
    - lxml >=5.3.0
    - tqdm >=4.67.1
    - pathos >=0.3.3
    - cryptography >=42.0.8

test:
  imports:
    - translators
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/UlionTse/translators
  summary: Translators is a library which aims to bring free, multiple, enjoyable translation to individuals and students in Python.
  dev_url: https://github.com/UlionTse/translators
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - UlionTse
