{% set name = "translators" %}
{% set version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/translators-{{ version }}.tar.gz
  sha256: 79962830fce5314810f7266e7c6555c4387883ee12d86072e14a03c1bb3707a8

build:
  entry_points:
    - fanyi = translators.cli:translate_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - httpx >=0.28.1
    - requests >=2.32.3
    - niquests >=3.14.0
    - exejs >=0.0.4
    - lxml >=5.3.0
    - tqdm >=4.67.1
    - pathos >=0.3.4
    - cryptography >=42.0.4

test:
  imports:
    - translators
  commands:
    - pip check
    - fanyi --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/UlionTse/translators
  summary: Translators is a library which aims to bring free, multiple, enjoyable translation to individuals and students in Python.
  dev_url: https://github.com/UlionTse/translators
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - UlionTse
