{% set name = "translators" %}
{% set version = "5.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/translators-{{ version }}.tar.gz
  sha256: 1661d5e70aa0e48e43cb344e396a90e43b8fa3257bfafdd393ee1cee9832cb59

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.29.0
    - pyexecjs >=1.5.1
    - lxml >=4.9.1
    - tqdm >=4.65.0
    - pathos >=0.2.9
    - cryptography >=38.0.1

test:
  imports:
    - translators
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/UlionTse/translators
  summary: Translators is a library which aims to bring free, multiple, enjoyable translation to individuals and students in Python.
  dev_url: https://github.com/UlionTse/translators
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - UlionTse
