{% set name = "translators" %}
{% set version = "5.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/translators-{{ version }}.tar.gz
  sha256: e219708d419f9b2b502c8ad61b7f6fd9771cd1ff80632df069c027a69da0c72d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - requests >=2.29.0
    - pyexecjs >=1.5.1
    - lxml >=4.9.1
    - tqdm >=4.65.0
    - pathos >=0.2.9
    - cryptography >=38.0.1

test:
  imports:
    - translators
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/UlionTse/translators
  summary: Translators is a library which aims to bring free, multiple, enjoyable translation to individuals and students in Python.
  dev_url: https://github.com/UlionTse/translators
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - UlionTse
